#
## Makefile for the project
#
## Author: RockyChing <zdh1021680772@163.com>

TARGET = none

TOP_DIR := .

SRCDIRS := .
SRCFIXS := .c

all: $(TARGET)

clean:
	rm -rf $(TOP_DIR)/output/* $(TOP_DIR)/project/DebugConfig $(TOP_DIR)/project/Listings
